name: Update Birthday Calendar

on:
  schedule:
    - cron: '0 21 * * *'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Update calendar
      env:
        GOOGLE_API_TOKEN: ${{ secrets.GOOGLE_API_TOKEN }}
        GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
        GOOGLE_AUTH_PROVIDER_X509_CERT_URL: ${{ vars.GOOGLE_AUTH_PROVIDER_X509_CERT_URL }}
        GOOGLE_AUTH_URI: ${{ vars.GOOGLE_AUTH_URI }}
        GOOGLE_TOKEN_URI: ${{ vars.GOOGLE_TOKEN_URI }}
      run: |
        python ./scripts/update_calendar.py

    - name: Upload to Cloudflare Pages
      env:
        CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        CLOUDFLARE_PAGES_PROJECT_NAME: ${{ vars.CLOUDFLARE_PAGES_PROJECT_NAME }}
        CLOUDFLARE_PAGES_API_TOKEN: ${{ secrets.CLOUDFLARE_PAGES_API_TOKEN }}
      run: |
        curl -X POST "https://api.cloudflare.com/client/v4/accounts/${CLOUDFLARE_ACCOUNT_ID}/pages/projects/${CLOUDFLARE_PAGES_PROJECT_NAME}/deployments" \
          -H "Authorization: Bearer ${CLOUDFLARE_PAGES_API_TOKEN}" \
          -F "file=@data/birthdays.ics"